spring.application.name=sgfpe
spring.data.mongodb.uri=mongodb+srv://20233tn180:202004@cluster-spring-mongodb.igaro.mongodb.net/?retryWrites=true&w=majority&appName=Cluster-Spring-MongoDB
spring.data.mongodb.database=sgfpe_db